import type { Company, Deal, Person, TeamMember } from "./types";

export const team: TeamMember[] = [
  { id: "u1", name: "Tommaso Seita", email: "tommaso@wibo.app", initials: "TS", color: "#5b5fef" },
  { id: "u2", name: "Davide Rossi", email: "davide@wibo.app", initials: "DR", color: "#10b981" },
  { id: "u3", name: "Giulia Bianchi", email: "giulia@wibo.app", initials: "GB", color: "#f59e0b" },
  { id: "u4", name: "Marco Verdi", email: "marco@wibo.app", initials: "MV", color: "#a78bfa" },
];

export const companies: Company[] = [
  {
    id: "c1",
    name: "Linear",
    domain: "linear.app",
    industry: "Software",
    size: "51-200",
    location: "San Francisco, CA",
    arr: 12_500_000,
    ownerId: "u1",
    createdAt: "2026-01-12",
    description: "Issue tracking tool for modern software teams.",
  },
  {
    id: "c2",
    name: "Notion",
    domain: "notion.so",
    industry: "Productivity",
    size: "201-1000",
    location: "San Francisco, CA",
    arr: 48_000_000,
    ownerId: "u2",
    createdAt: "2025-11-03",
    description: "All-in-one connected workspace.",
  },
  {
    id: "c3",
    name: "Vercel",
    domain: "vercel.com",
    industry: "Cloud",
    size: "201-1000",
    location: "Remote",
    arr: 95_000_000,
    ownerId: "u1",
    createdAt: "2025-09-21",
  },
  {
    id: "c4",
    name: "Stripe",
    domain: "stripe.com",
    industry: "Fintech",
    size: "1000+",
    location: "Dublin, IE",
    arr: 350_000_000,
    ownerId: "u3",
    createdAt: "2025-06-14",
  },
  {
    id: "c5",
    name: "Figma",
    domain: "figma.com",
    industry: "Design",
    size: "1000+",
    location: "San Francisco, CA",
    arr: 280_000_000,
    ownerId: "u2",
    createdAt: "2025-04-02",
  },
  {
    id: "c6",
    name: "Loom",
    domain: "loom.com",
    industry: "Video",
    size: "201-1000",
    location: "San Francisco, CA",
    arr: 70_000_000,
    ownerId: "u4",
    createdAt: "2025-03-10",
  },
  {
    id: "c7",
    name: "Pitch",
    domain: "pitch.com",
    industry: "Productivity",
    size: "51-200",
    location: "Berlin, DE",
    arr: 9_500_000,
    ownerId: "u3",
    createdAt: "2025-02-19",
  },
  {
    id: "c8",
    name: "Raycast",
    domain: "raycast.com",
    industry: "Software",
    size: "11-50",
    location: "London, UK",
    arr: 5_200_000,
    ownerId: "u1",
    createdAt: "2025-01-30",
  },
  {
    id: "c9",
    name: "Arc Browser",
    domain: "arc.net",
    industry: "Software",
    size: "51-200",
    location: "New York, NY",
    arr: 0,
    ownerId: "u4",
    createdAt: "2024-12-05",
  },
  {
    id: "c10",
    name: "Mistral AI",
    domain: "mistral.ai",
    industry: "Artificial Intelligence",
    size: "51-200",
    location: "Paris, FR",
    arr: 30_000_000,
    ownerId: "u2",
    createdAt: "2024-11-22",
  },
];

export const people: Person[] = [
  {
    id: "p1",
    firstName: "Karri",
    lastName: "Saarinen",
    email: "karri@linear.app",
    role: "CEO",
    companyId: "c1",
    ownerId: "u1",
    lastContactedAt: "2026-05-20",
    createdAt: "2026-01-12",
  },
  {
    id: "p2",
    firstName: "Tuomas",
    lastName: "Artman",
    email: "tuomas@linear.app",
    role: "CTO",
    companyId: "c1",
    ownerId: "u1",
    lastContactedAt: "2026-04-18",
    createdAt: "2026-01-12",
  },
  {
    id: "p3",
    firstName: "Ivan",
    lastName: "Zhao",
    email: "ivan@notion.so",
    role: "Co-founder & CEO",
    companyId: "c2",
    ownerId: "u2",
    lastContactedAt: "2026-05-08",
    createdAt: "2025-11-03",
  },
  {
    id: "p4",
    firstName: "Akshay",
    lastName: "Kothari",
    email: "akshay@notion.so",
    role: "COO",
    companyId: "c2",
    ownerId: "u2",
    lastContactedAt: "2026-03-29",
    createdAt: "2025-11-04",
  },
  {
    id: "p5",
    firstName: "Guillermo",
    lastName: "Rauch",
    email: "guillermo@vercel.com",
    role: "CEO",
    companyId: "c3",
    ownerId: "u1",
    lastContactedAt: "2026-05-22",
    createdAt: "2025-09-21",
  },
  {
    id: "p6",
    firstName: "Patrick",
    lastName: "Collison",
    email: "patrick@stripe.com",
    role: "CEO",
    companyId: "c4",
    ownerId: "u3",
    lastContactedAt: "2026-02-14",
    createdAt: "2025-06-14",
  },
  {
    id: "p7",
    firstName: "Dylan",
    lastName: "Field",
    email: "dylan@figma.com",
    role: "Co-founder & CEO",
    companyId: "c5",
    ownerId: "u2",
    lastContactedAt: "2026-04-30",
    createdAt: "2025-04-02",
  },
  {
    id: "p8",
    firstName: "Joe",
    lastName: "Thomas",
    email: "joe@loom.com",
    role: "Co-founder",
    companyId: "c6",
    ownerId: "u4",
    lastContactedAt: "2026-01-05",
    createdAt: "2025-03-10",
  },
  {
    id: "p9",
    firstName: "Christian",
    lastName: "Reber",
    email: "christian@pitch.com",
    role: "CEO",
    companyId: "c7",
    ownerId: "u3",
    lastContactedAt: "2026-05-15",
    createdAt: "2025-02-19",
  },
  {
    id: "p10",
    firstName: "Thomas",
    lastName: "Paul Mann",
    email: "thomas@raycast.com",
    role: "Co-founder",
    companyId: "c8",
    ownerId: "u1",
    lastContactedAt: "2026-05-21",
    createdAt: "2025-01-30",
  },
  {
    id: "p11",
    firstName: "Josh",
    lastName: "Miller",
    email: "josh@arc.net",
    role: "CEO",
    companyId: "c9",
    ownerId: "u4",
    lastContactedAt: "2025-12-19",
    createdAt: "2024-12-05",
  },
  {
    id: "p12",
    firstName: "Arthur",
    lastName: "Mensch",
    email: "arthur@mistral.ai",
    role: "CEO",
    companyId: "c10",
    ownerId: "u2",
    lastContactedAt: "2026-05-23",
    createdAt: "2024-11-22",
  },
  {
    id: "p13",
    firstName: "Cam",
    lastName: "Adams",
    email: "cam@linear.app",
    role: "Co-founder",
    companyId: "c1",
    ownerId: "u1",
    lastContactedAt: "2026-04-02",
    createdAt: "2026-01-12",
  },
  {
    id: "p14",
    firstName: "John",
    lastName: "Collison",
    email: "john@stripe.com",
    role: "President",
    companyId: "c4",
    ownerId: "u3",
    lastContactedAt: "2026-03-11",
    createdAt: "2025-06-14",
  },
];

export const deals: Deal[] = [
  {
    id: "d1",
    name: "Linear — Enterprise expansion",
    value: 120_000,
    currency: "EUR",
    stage: "negotiation",
    companyId: "c1",
    primaryContactId: "p1",
    ownerId: "u1",
    expectedCloseDate: "2026-06-12",
    probability: 70,
    createdAt: "2026-03-01",
  },
  {
    id: "d2",
    name: "Notion — Workspace AI add-on",
    value: 85_000,
    currency: "EUR",
    stage: "proposal",
    companyId: "c2",
    primaryContactId: "p3",
    ownerId: "u2",
    expectedCloseDate: "2026-06-30",
    probability: 55,
    createdAt: "2026-04-10",
  },
  {
    id: "d3",
    name: "Vercel — Edge compute migration",
    value: 240_000,
    currency: "USD",
    stage: "qualified",
    companyId: "c3",
    primaryContactId: "p5",
    ownerId: "u1",
    expectedCloseDate: "2026-08-01",
    probability: 35,
    createdAt: "2026-04-22",
  },
  {
    id: "d4",
    name: "Stripe — Billing automation",
    value: 510_000,
    currency: "EUR",
    stage: "negotiation",
    companyId: "c4",
    primaryContactId: "p6",
    ownerId: "u3",
    expectedCloseDate: "2026-07-05",
    probability: 65,
    createdAt: "2026-02-18",
  },
  {
    id: "d5",
    name: "Figma — Design ops rollout",
    value: 175_000,
    currency: "EUR",
    stage: "won",
    companyId: "c5",
    primaryContactId: "p7",
    ownerId: "u2",
    expectedCloseDate: "2026-05-10",
    probability: 100,
    createdAt: "2026-01-08",
  },
  {
    id: "d6",
    name: "Loom — Sales enablement",
    value: 42_000,
    currency: "EUR",
    stage: "lead",
    companyId: "c6",
    primaryContactId: "p8",
    ownerId: "u4",
    expectedCloseDate: "2026-09-15",
    probability: 15,
    createdAt: "2026-05-12",
  },
  {
    id: "d7",
    name: "Pitch — Annual renewal",
    value: 32_000,
    currency: "EUR",
    stage: "qualified",
    companyId: "c7",
    primaryContactId: "p9",
    ownerId: "u3",
    expectedCloseDate: "2026-07-20",
    probability: 45,
    createdAt: "2026-04-30",
  },
  {
    id: "d8",
    name: "Raycast — Team plan upgrade",
    value: 18_500,
    currency: "EUR",
    stage: "proposal",
    companyId: "c8",
    primaryContactId: "p10",
    ownerId: "u1",
    expectedCloseDate: "2026-06-25",
    probability: 60,
    createdAt: "2026-04-15",
  },
  {
    id: "d9",
    name: "Arc Browser — Pilot",
    value: 12_000,
    currency: "USD",
    stage: "lead",
    companyId: "c9",
    primaryContactId: "p11",
    ownerId: "u4",
    expectedCloseDate: "2026-08-12",
    probability: 10,
    createdAt: "2026-05-18",
  },
  {
    id: "d10",
    name: "Mistral AI — Inference platform",
    value: 380_000,
    currency: "EUR",
    stage: "qualified",
    companyId: "c10",
    primaryContactId: "p12",
    ownerId: "u2",
    expectedCloseDate: "2026-09-30",
    probability: 40,
    createdAt: "2026-05-02",
  },
  {
    id: "d11",
    name: "Linear — Onboarding success plan",
    value: 22_000,
    currency: "EUR",
    stage: "lost",
    companyId: "c1",
    primaryContactId: "p13",
    ownerId: "u1",
    expectedCloseDate: "2026-04-30",
    probability: 0,
    createdAt: "2026-02-22",
  },
];

export function companyById(id: string) {
  return companies.find((c) => c.id === id);
}

export function personById(id: string) {
  return people.find((p) => p.id === id);
}

export function teamMemberById(id: string) {
  return team.find((m) => m.id === id);
}

export function peopleByCompany(companyId: string) {
  return people.filter((p) => p.companyId === companyId);
}

export function dealsByCompany(companyId: string) {
  return deals.filter((d) => d.companyId === companyId);
}
